### ISSUE TITLE
How to build this project?  dependencies:  com.varabyte.kobweb.application is missing

### ISSUE THREAD

**Issue by sunyuyangg555** [bitspittle/racketeer#6]
I could not build this project. I change the version from 0.11.5-SHAPSHOT to 0.11.4, but is not ok.
```
Plugin [id: 'com.varabyte.kobweb.application', version: '0.11.4'] was not found in any of the following sources
```

**Comment by bitspittle** [comment]
Ah, I'm not sure why it doesn't build, but I'm actually not expecting anyone to run this project yet, and I won't have time to help with issues with it yet.

 In fact, I've had it set to private for a while but only opened it up today just to share some code examples. As you can see, there's no README set up yet. It's totally unprepared....

Still, if you have Kobweb installed, you should be able to cd into racketeer/site and type `kobweb run`

If you don't have Kobweb installed, please see https://github.com/varabyte/kobweb for more information.

**Comment by sunyuyangg555** [comment]
This project is awesome, I  want  to see the demo result  very much , especially the design of the script.

**Comment by bitspittle** [comment]
Try running this: `./gradlew :limp-interpreter:run`

The scripting language is currently called `Limp` which is because it's
inspired by `Lisp` and it's multiplatform.

Eventually I plan to move it out into its own separate project. You can
actually find a partial README under the limp/ folder.

**Comment by sunyuyangg555** [comment]
Thank you very much. I've  got it up and runing on my mac. the windows is not ok, maybe is the network connecting proprem.

**Comment by bitspittle** [comment]
Ah, Windows... 😭

Just an FYI, I'll probably be extracting the scripting language out to its
own project soon. It's much more ready to share with the world than the
card game.
